### ISSUE TITLE
spec2nii / Bruker / Paravision6.0.1

### ISSUE THREAD

**Issue by benhibou** [isi-nmr/brukerapi-python#15]
Hello,

I came across spec2nii, and we are interested to use it in order to extract the MRS voxel into the nifti format. Trying to use it I have stumbled along the following errors:
spec2nii bruker -m FID  8/fid
Traceback (most recent call last):
  File "/home/spectro/anaconda3/bin/spec2nii", line 10, in <module>
    sys.exit(main())
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 666, in main
    spec2nii(*args)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 283, in __init__
    args.func(args)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 635, in bruker
    self.imageOut, self.fileoutNames = read_bruker(args)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/bruker.py", line 44, in read_bruker
    for data, orientation, dwelltime, meta, name in yield_bruker(args):
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/bruker.py", line 79, in yield_bruker
    parameter_files=['method'])
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/dataset.py", line 199, in __init__
    self.load()
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/dataset.py", line 273, in load
    self.load_data()
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/dataset.py", line 521, in load_data
    self._data = self._read_data()
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/dataset.py", line 531, in _read_data
    return self._schema.deserialize(data, self._schema.layouts)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/schemas.py", line 162, in deserialize
    data = self._acquisitions_to_encode(data, layouts)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/schemas.py", line 200, in _acquisitions_to_encode
    return np.reshape(data, layouts['encoding_space'], order='F')
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 16384 into shape (4096,1)

On another dataset the last line of the message was:
ValueError: cannot reshape array of size 8192 into shape (2048,1)

The other lines being similar. Any hint?

Thank you,

Benoit

**Comment by benhibou** [comment]
Alternatively, spec2nii works in one instance when instead of passing:

- spec2nii bruker -m FID 6/fid which gave an error as specified above

one issues:

- spec2nii bruker -m FID 6

where "6" is the directory containing the data. However in the other instance, in our case the "8" directory, issuing the command:

-  spec2nii bruker -m FID 8 results in the following error:
spec2nii bruker  -m FID 8/
Traceback (most recent call last):
  File "/home/spectro/anaconda3/bin/spec2nii", line 10, in <module>
    sys.exit(main())
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 666, in main
    spec2nii(*args)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 283, in __init__
    args.func(args)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 635, in bruker
    self.imageOut, self.fileoutNames = read_bruker(args)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/bruker.py", line 44, in read_bruker
    for data, orientation, dwelltime, meta, name in yield_bruker(args):
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/spec2nii/bruker.py", line 94, in yield_bruker
    with dataset as d:
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/dataset.py", line 204, in __enter__
    self.load()
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/dataset.py", line 272, in load
    self.load_schema()
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/dataset.py", line 487, in load_schema
    self._schema = SchemaFid(self)
  File "/home/spectro/anaconda3/lib/python3.7/site-packages/brukerapi/schemas.py", line 73, in __init__
    raise MissingProperty(property)
brukerapi.exceptions.MissingProperty: Dataset is missing the scheme_id property. We can offer some help, please contact us via https://github.com/isi-nmr/brukerapi-python

**Comment by headmeister** [comment]
Hi @benhibou, sorry for such a late response, I am a new maintainer of this repo. Is this issue still relevant? If, yes I would need more context. Especially since this is issue reported from a different software that only uses brukerapi. The error clearly comes from the brukerapi itself, however without the data it is hard to trace. 

The first error could be connected to an issue where some sequences were not loading all of the FID data, so this might be fixed in the newest version (CPMG was such an example or EPSI). 

The second error simply says it cannot import the given sequence, since it does not know it. If this is e.g. a custom pulse sequence the bruker api will not be able to load it, as it does not know how to reshape the FID. If it is a original Bruker sequence we should be able to load it, so then it would be definitely a bug, but again I would need at least the sequence and its settings. Or the data itself at best in order to trace the issue.
